language: "ruby"
script: "bundle exec rake"
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - jruby-18mode
  - jruby-19mode
  - rbx-18mode
  - rbx-19mode
  - ree
gemfile:
  - Gemfile
  - gemfiles/2.0.gemfile
  - gemfiles/2.3.gemfile
  - gemfiles/3.0.gemfile
  - gemfiles/3.2.gemfile
